spring.application.name=hospitalManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.datasource.username=postgres
spring.datasource.password=Djay25


spring.jpa.hibernate.ddl-auto=create 
spring.jpa.show-sql=true 
#spring.jpa.properties.hibernate.format_sql=false //Format the hibernate queries, statements

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

server.servlet.context-path=/api/v1

#Security Config
#spring.security.user.name=Dj
#spring.security.user.password=pass

spring.jackson.serialization.indent_output=true

jwt.secretKey = iegf683g98hnoiaenf8y4g7rh3rbqojwbf793

#spring.security.oauth2.client.registration.google.client-id = efqefs    Used in applicaton.yml file
#spring.security.oauth2.client.registration.google.client-secret = efqefs